import {
  Wallet,
  CreditCard,
  Banknote,
  PiggyBank,
  Coins,
  DollarSign,
  Euro,
  Landmark,
  Building2,
  Briefcase,
  ShoppingCart,
  ShoppingBag,
  Utensils,
  Coffee,
  Beer,
  Pizza,
  Car,
  Bike,
  Bus,
  Plane,
  Train,
  Fuel,
  House,
  Home,
  Bed,
  Sofa,
  Lightbulb,
  Wifi,
  Phone,
  Smartphone,
  Tv,
  Monitor,
  Headphones,
  Music,
  Film,
  Gamepad2,
  Book,
  GraduationCap,
  Stethoscope,
  Pill,
  Heart,
  Dumbbell,
  Shirt,
  Gift,
  Cake,
  PartyPopper,
  PawPrint,
  Baby,
  Wrench,
  Hammer,
  Sparkles,
  TrendingUp,
  TrendingDown,
  Receipt,
  ReceiptText,
  Tag,
  Tags,
  Star,
  Bookmark,
  Trophy,
  Target,
  Repeat,
  Calendar,
  Clock,
  MapPin,
  Sun,
  Umbrella,
  TreePine,
  Flower2,
  Cigarette,
  Wine,
  Soup,
  IceCream,
  Apple,
  type LucideIcon,
} from 'lucide-react';

export const ICON_POOL: Record<string, LucideIcon> = {
  // Soldi & conti
  wallet: Wallet,
  'credit-card': CreditCard,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  coins: Coins,
  'dollar-sign': DollarSign,
  euro: Euro,
  landmark: Landmark,
  building: Building2,
  briefcase: Briefcase,
  // Spesa & cibo
  cart: ShoppingCart,
  bag: ShoppingBag,
  utensils: Utensils,
  coffee: Coffee,
  beer: Beer,
  pizza: Pizza,
  wine: Wine,
  soup: Soup,
  'ice-cream': IceCream,
  apple: Apple,
  cake: Cake,
  // Trasporti
  car: Car,
  bike: Bike,
  bus: Bus,
  plane: Plane,
  train: Train,
  fuel: Fuel,
  // Casa
  house: House,
  home: Home,
  bed: Bed,
  sofa: Sofa,
  lightbulb: Lightbulb,
  wifi: Wifi,
  // Tech & svago
  phone: Phone,
  smartphone: Smartphone,
  tv: Tv,
  monitor: Monitor,
  headphones: Headphones,
  music: Music,
  film: Film,
  gaming: Gamepad2,
  // Salute & istruzione
  book: Book,
  graduation: GraduationCap,
  stethoscope: Stethoscope,
  pill: Pill,
  heart: Heart,
  dumbbell: Dumbbell,
  // Persona
  shirt: Shirt,
  gift: Gift,
  party: PartyPopper,
  pet: PawPrint,
  baby: Baby,
  cigarette: Cigarette,
  // Lavori
  wrench: Wrench,
  hammer: Hammer,
  sparkles: Sparkles,
  // Generici
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  receipt: Receipt,
  'receipt-text': ReceiptText,
  tag: Tag,
  tags: Tags,
  star: Star,
  bookmark: Bookmark,
  trophy: Trophy,
  target: Target,
  repeat: Repeat,
  calendar: Calendar,
  clock: Clock,
  pin: MapPin,
  sun: Sun,
  umbrella: Umbrella,
  tree: TreePine,
  flower: Flower2,
};

export const ICON_KEYS = Object.keys(ICON_POOL);

/**
 * Risolve una chiave in un componente icona. Se la chiave non è registrata,
 * ritorna `Wallet` come fallback (così le icone "vecchie" non rompono nulla).
 */
export function getIcon(key: string | null | undefined): LucideIcon {
  if (!key) return Wallet;
  return ICON_POOL[key] ?? Wallet;
}
